<div class="col2-set">
	<div class="col-1">
		<div class="box">
			<div class="box-title">
				<h3><?php echo $this->__('Contact Information') ?></h3>
				<a href="<?php echo $this->getUrl('customer/account/edit') ?>"><?php echo $this->__('Edit') ?></a>
			</div>
			<div class="box-content">
				<p>
					<?php echo $this->htmlEscape($this->getCustomer()->getName()) ?><br />
					<?php echo $this->htmlEscape($this->getCustomer()->getEmail()) ?><br />
					<a href="<?php echo $this->getChangePasswordUrl() ?>"><?php echo $this->__('Change Password') ?></a>
				</p>
			</div>
		</div>
	</div>
	<?php if ($this->isNewsletterEnabled()): ?>
	<div class="col-2">
		<div class="box">
			<div class="box-title">
				<h3><?php echo $this->__('Newsletters') ?></h3>
				<a href="<?php echo $this->getUrl('newsletter/manage') ?>"><?php echo $this->__('Edit') ?></a>
			</div>
			<div class="box-content">
				<?php
					$subscriptions = $this->getSubscriptions();
				   if ($subscriptions['count'] > 0)
					{
						echo "<p>You are currently subscribed to: <br />" . $subscriptions['publication']['name'] . "</p>";
						
						if ($subscriptions['list_count'] > 0)
						{
							echo "<strong>Interests:</strong>";
							echo "<ul>";
							foreach ($subscriptions['lists'] as $list)
							{
								echo "<li>{$list['name']}</li>";
							}
							echo "</ul>";
						}
					}
					else
						echo "<p>" . $this->__('You are currently not subscribed to any newsletter.') . "</p>";
				?>
			</div>
		</div>
	</div>
	<?php endif; ?>
</div>
