<?php

$subscriptions = $this->getSubscriptions();
$publication_data = $subscriptions['publication'];
$list_data = $subscriptions['lists'];

?>
<div class="page-title">
	<h1><?php echo $this->__('Newsletter Subscription'); ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getUrl('emaildirect/customer_account/saveadditional'); ?>" name="emaildirect_additional" id="emaildirect-additional" method="post">
	<div class="fieldset">
		<?php echo $this->getBlockHtml('formkey'); ?>
		<ul class="emaildirect-additional-lists">
			<li class="listdata">General Subscription: <?php echo $this->showCheckbox($publication_data, 'publication'); ?>
		</ul>
		<br />
		<?php if (count($list_data) > 0): ?>
		<strong>Interests:</strong>
		<ul class="emaildirect-additional-lists">
			<?php foreach($list_data as $list):	?>
				<li class="listdata">
					<?php echo $this->showCheckbox($list); ?>
				</li>
			<?php endforeach; ?>
		</ul>
		<?php endif; ?>
	</div>
	<input type="hidden" name="state" value="" id="form-state" />
	<div class="buttons-set">
		<button type="submit" title="<?php echo $this->__('Save') ?>" class="button"><span><span><?php echo $this->__('Save') ?></span></span></button>
	</div>
</form>
<script type="text/javascript">
	document.observe("dom:loaded", function()
	{
		removeManageNewsletter();
		$$('.emaildirect-publication-subscriber').first().observe('change', function()
		{
			var groupings = $$('.emaildirect-list-subscriber');
			
			if(groupings)
			{
				if(this.checked)
				{
					groupings.each(function(index, item)
					{
						index.removeAttribute('disabled');
					}.bind(this));
				}
				else
				{
					groupings.each(function(index, item)
					{
						index.writeAttribute('disabled', 'disabled');
					}.bind(this));
				}
			}
		});
		$('form-state').writeAttribute('value', $('emaildirect-additional').serialize());
	});
</script>
