<?php

//$_order = $this->getOrder();
//$_send_field = $this->getSendField();
$_date_sent = $this->getEmailDirectDate();
//$_can_send_orders = $this->canSendOrders();

$cart = Mage::helper('emaildirect/diagnostic')->getAbandonedCart();

//Zend_debug::dump($quote->getData());

?>

<div class="box-left">
	<!--Diagnostic Information-->
	<div class="entry-edit">
		<div class="entry-edit-head">
			<h4 class="icon-head head-edit-form fieldset-legend">EmailDirect Diagnostics for Abandoned Cart</h4>
		</div>
		<div class="fieldset">
			<table cellspacing="0" class="form-list">
			<tbody>
			<tr>
				<td class="label"><label>Sent to EmailDirect</label></td>
				<td class="value"><strong>
					<?php if ($_date_sent == null): ?>
						<span style='color: red'>Not Sent</span>
					<?php else: ?>
						<span style='color: green'><?php echo $this->formatDate($_date_sent, 'medium', true); ?></span>
					<?php endif; ?>
				</strong></td>
			</tr>
			<tr>
				<td class="label"><label>EmailDirect Status</label></td>
				<td class="value"><strong>
					<?php if (!$this->isEmailDirectEnabled()): ?>
						<div style='color: red'>Disabled for this Store</div>
					<?php elseif (!$this->isEmailDirectSetup()): ?>
						<div style='color: red'>Api Key Missing/Invalid</div>
					<?php else: ?>
						<div style='color: green'>Enabled</div>
						<?php if (1 == 0 || !$this->isAbandonedEnabled()): ?>
							<div style='color: red'>Abandoned Carts are disabled</div>
						<?php endif; ?>
					<?php endif; ?>
				</strong></td>
			</tr>
			</tbody>
			</table>
		</div>
	</div>
</div>