<div id="<?php echo $this->getElement()->getHtmlId(); ?>" style='display:none'></div>
<p>You can retrieve an API Key by going to your EmailDirect account and clicking on Account Setup, then navigating to the API Keys tab.</p>
<br /> 
<p>If you do not have an EmailDirect account, please email us at <a href="mailto:Sales@EmailDirect.com">Sales@EmailDirect.com</a> or call 916-439-6948.  You can also visit our website at <a href="http://www.EmailDirect.com">http://www.EmailDirect.com</a> to learn more about this integration and other features that we offer.</p>